# Generated by Django 4.1 on 2023-11-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "stock_symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("industry_classification", models.CharField(max_length=255)),
                ("market", models.CharField(max_length=20)),
                ("company_profile", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscriptions",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subscription_status", models.CharField(max_length=20)),
                ("notification_preferences", models.CharField(max_length=255)),
                (
                    "stock_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stocks",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPredictionRequests",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prediction_interval",
                    models.CharField(choices=[("M", "分钟"), ("H", "小时")], max_length=1),
                ),
                ("request_timestamp", models.DateTimeField()),
                ("prediction_result", models.CharField(max_length=255)),
                (
                    "stock_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stocks",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalIndicators",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "moving_average",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "relative_strength_index",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stochastic_oscillator",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stocks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prices",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.PositiveIntegerField()),
                (
                    "adjusted_close",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stocks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("news_title", models.CharField(max_length=255)),
                ("news_content", models.TextField()),
                (
                    "stock_symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stocks",
                    ),
                ),
            ],
        ),
    ]
