# Generated by Django 4.2 on 2023-12-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "index_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("index_name", models.CharField(max_length=255)),
                ("market", models.CharField(max_length=20)),
                ("index_information", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "stock_symbol",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("market", models.CharField(max_length=20)),
                ("company_profile", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subscription_status", models.CharField(max_length=20)),
                ("notification_preferences", models.CharField(max_length=255)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPredictionRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("prediction_interval", models.CharField(max_length=2)),
                ("timestamp", models.DateTimeField()),
                ("prediction_result", models.TextField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserIndexSubscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subscription_status", models.CharField(max_length=20)),
                ("notification_preferences", models.CharField(max_length=255)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.index",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalIndicator",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "moving_average",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "relative_strength_index",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stochastic_oscillator",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.IntegerField()),
                (
                    "adjusted_close",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("news_title", models.CharField(max_length=255)),
                ("news_content", models.TextField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks_app.stock",
                    ),
                ),
            ],
        ),
    ]
