# Generated by Django 4.2.7 on 2023-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=100)),
                ("latest_close_price", models.FloatField()),
                ("change_amount", models.FloatField()),
                ("change_percentage", models.FloatField()),
            ],
        ),
    ]
