# Generated by Django 4.1 on 2023-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks_app", "0002_index_price_userindexsubscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="industry_classification",
        ),
        migrations.AlterField(
            model_name="stock",
            name="company_profile",
            field=models.TextField(blank=True, null=True),
        ),
    ]
