# Generated by Django 4.1 on 2023-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks_app", "0003_remove_stock_industry_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="index",
            name="index_information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
