# Generated by Django 4.1 on 2023-11-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configurations",
            fields=[
                (
                    "config_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("config_value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DataSources",
            fields=[
                ("data_source_id", models.AutoField(primary_key=True, serialize=False)),
                ("data_source_name", models.CharField(max_length=255)),
                ("data_quality", models.CharField(max_length=20)),
                ("data_integrity", models.CharField(max_length=20)),
                ("backup_status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("log_type", models.CharField(max_length=20)),
                ("log_content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvents",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=20)),
                ("event_description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servers",
            fields=[
                ("server_id", models.AutoField(primary_key=True, serialize=False)),
                ("server_name", models.CharField(max_length=255)),
                ("configuration", models.TextField()),
                ("load_balancing_status", models.CharField(max_length=20)),
                ("last_monitored_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserPermissions",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.roles",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedbacks",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback_content", models.TextField()),
                ("submission_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Models",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=255)),
                ("training_status", models.CharField(max_length=20)),
                ("model_performance", models.CharField(max_length=255)),
                (
                    "data_source_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.datasources",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrators",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.roles",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
    ]
