# Generated by Django 4.1 on 2023-11-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("log_type", models.CharField(max_length=20)),
                ("log_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=20)),
                ("event_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                ("server_id", models.AutoField(primary_key=True, serialize=False)),
                ("server_name", models.CharField(max_length=255)),
                ("configuration", models.TextField()),
                ("load_balancing_status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback_content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="UserPermissions",
            new_name="Administrator",
        ),
        migrations.RenameModel(
            old_name="Configurations",
            new_name="Configuration",
        ),
        migrations.RenameModel(
            old_name="DataSources",
            new_name="DataSource",
        ),
        migrations.RenameModel(
            old_name="Models",
            new_name="Model",
        ),
        migrations.RemoveField(
            model_name="administrators",
            name="role_id",
        ),
        migrations.RemoveField(
            model_name="administrators",
            name="user",
        ),
        migrations.DeleteModel(
            name="Logs",
        ),
        migrations.DeleteModel(
            name="SecurityEvents",
        ),
        migrations.DeleteModel(
            name="Servers",
        ),
        migrations.RemoveField(
            model_name="userfeedbacks",
            name="user",
        ),
        migrations.RenameField(
            model_name="administrator",
            old_name="record_id",
            new_name="admin_id",
        ),
        migrations.RenameField(
            model_name="administrator",
            old_name="role",
            new_name="role_id",
        ),
        migrations.RenameModel(
            old_name="Roles",
            new_name="Role",
        ),
        migrations.DeleteModel(
            name="Administrators",
        ),
        migrations.DeleteModel(
            name="UserFeedbacks",
        ),
        migrations.AddField(
            model_name="userpermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_app.role"
            ),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users_app.user"
            ),
        ),
    ]
